- name: Enable Homebrew bundle tap
  homebrew_tap:
    name: homebrew/bundle

- name: Install apps using Brewfile
  shell: brew bundle install --file="{{brewfile|default(Brewfile)}}"
  ignore_errors: true
  #when: bundle_check_result|failed

- name: Check if Brewfile contains updates
  shell: brew bundle check --file="{{brewfile|default(Brewfile)}}"
  register: bundle_check_result
  ignore_errors: true

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
